# Generated by Django 3.0.8 on 2020-08-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktracks', '0002_ktrack_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ktrack',
            name='cerated_at',
        ),
        migrations.RemoveField(
            model_name='ktrack',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ktrack',
            name='tittle',
        ),
        migrations.RemoveField(
            model_name='ktrack',
            name='url',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ktracks.Ktrack')),
            ],
        ),
    ]
