# Generated by Django 3.0.8 on 2020-08-15 14:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ktracks', '0003_auto_20200815_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktrack',
            name='cerated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ktrack',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ktrack',
            name='tittle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ktrack',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
