# Generated by Django 3.0.8 on 2020-08-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktracks', '0004_auto_20200815_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ktrack',
            old_name='cerated_at',
            new_name='created_at',
        ),
    ]
